<?php
/**
 * plazarecoleta functions and definitions
 *
 * The first function, plazarecoleta_setup(), sets up the theme by registering support
 * for various features in WordPress, such as post thumbnails, navigation menus, and the like.
 *
 * For information on hooks, actions, and filters, see http://codex.wordpress.org/Plugin_API.
 *
 * @package WordPress
 * @subpackage plazarecoleta
 * @since plazarecoleta 1.0
 */
if ( ! isset( $content_width ) )
	$content_width = 1044;

/** Tell WordPress to run plazarecoleta_setup() when the 'after_setup_theme' hook is run. */
add_action( 'after_setup_theme', 'plazarecoleta_setup' );

if ( ! function_exists( 'plazarecoleta_setup' ) ):

/**
 * Set up theme defaults and registers support for various WordPress features.
 *
 * Note that this function is hooked into the after_setup_theme hook, which
 * runs before the init hook. The init hook is too late for some features, such
 * as indicating support post thumbnails.
 */
function plazarecoleta_setup() {
	
	// This theme styles the visual editor with editor-style.css to match the theme style.
	add_editor_style( array( 'css/editor-style.css', plazarecoleta_font_url() ) );
	
	// Enable support for Post Thumbnails, and declare two sizes.
	add_theme_support( 'post-thumbnails' );
	
	//custom size images
	add_image_size( 'featured-home-image', 1300, 700, true );
	add_image_size( 'gallery-page-image', 1000, 470, true );
	add_image_size( 'thumbnail-dept', 300, 225, true );
	add_image_size( 'thumbnail-floor', 300, 9999, false );
	
	// Create Theme Logotype Options Page
    require_once ( get_template_directory() . '/theme-admin/theme-options.php' );

	// Add default posts and comments RSS feed links to head
	add_theme_support( 'automatic-feed-links' );

	// Make theme available for translation
	// Translations can be filed in the /languages/ directory
	load_theme_textdomain( 'plazarecoleta', TEMPLATEPATH . '/languages' );

	$locale = get_locale();
	$locale_file = TEMPLATEPATH . "/languages/$locale.php";
	if ( is_readable( $locale_file ) )
		require_once( $locale_file );

	// This theme uses wp_nav_menu() in one location.
	register_nav_menus( array(
		'primary' => __( 'Navegación Lateral', 'plazarecoleta' ),
	) );
	
	register_nav_menus( array(
		'secondary' => __( 'Navegación Superior', 'plazarecoleta' ),
	) );
	
	register_nav_menus( array(
		'third' => __( 'Navegación Mobile', 'plazarecoleta' ),
	) );
	
	// This theme allows users to set a custom background
	global $wp_version;
	if ( version_compare( $wp_version, '3.4', '>=' ) ) 
     	add_theme_support( 'custom-background' ); 
    else
	add_custom_background( $args );
	
	// This theme allows users to set a custom header
	global $wp_version;
	if ( version_compare( $wp_version, '3.4', '>=' ) )
		add_theme_support( 'custom-header' );
	else
		add_custom_image_header( $args );
		
	$defaults = array(
	'default-image'          => get_template_directory_uri() . '/images/back/back.jpg',
	'random-default'         => false,
	'width'                  => 1200,
	'height'                 => 800,
	'flex-height'            => false,
	'flex-width'             => false,
	'default-text-color'     => '',
	'header-text'            => false,
	'uploads'                => true,
	'wp-head-callback'       => '',
	'admin-head-callback'    => '',
	'admin-preview-callback' => '',
	);
	add_theme_support( 'custom-header', $defaults );
	}
endif;

if ( ! function_exists( 'plazarecoleta_admin_header_style' ) ) :
/**
 * Styles the header image displayed on the Appearance > Header admin panel.
 *
 * Referenced via add_custom_image_header() in plazarecoleta_setup().
 *
 * @since plazarecoleta 1.0
 */
function plazarecoleta_admin_header_style() {
?>
<style type="text/css">
/* Shows the same border as on front end */
#headimg {
	border-bottom: 1px solid #000;
	border-top: 4px solid #000;
}
/* If NO_HEADER_TEXT is false, you would style the text with these selectors:
	#headimg #name { }
	#headimg #desc { }
*/
</style>
<?php
}
endif;

/**
 *
 *
 * @since plazarecoleta 1.0
 *
 * @param string $title Title generated by wp_title()
 * @param string $separator The separator passed to wp_title(). plazarecoleta uses a
 * 	vertical bar, "|", as a separator in header.php.
 * @return string The new title, ready for the <title> tag.
 */
function plazarecoleta_filter_wp_title( $title, $separator ) {
	// Don't affect wp_title() calls in feeds.
	if ( is_feed() )
		return $title;

	// The $paged global variable contains the page number of a listing of posts.
	// The $page global variable contains the page number of a single post that is paged.
	// We'll display whichever one applies, if we're not looking at the first page.
	global $paged, $page;

	if ( is_search() ) {
		// If we're a search, let's start over:
		$title = sprintf( __( 'Search results for %s', 'plazarecoleta' ), '"' . get_search_query() . '"' );
		// Add a page number if we're on page 2 or more:
		if ( $paged >= 2 )
			$title .= " $separator " . sprintf( __( 'Page %s', 'plazarecoleta' ), $paged );
		// Add the site name to the end:
		$title .= " $separator " . get_bloginfo( 'name', 'display' );
		// We're done. Let's send the new title back to wp_title():
		return $title;
	}

	// Otherwise, let's start by adding the site name to the end:
	$title .= get_bloginfo( 'name', 'display' );

	// If we have a site description and we're on the home/front page, add the description:
	$site_description = get_bloginfo( 'description', 'display' );
	if ( $site_description && ( is_home() || is_front_page() ) )
		$title .= " $separator " . $site_description;

	// Add a page number if necessary:
	if ( $paged >= 2 || $page >= 2 )
		$title .= " $separator " . sprintf( __( 'Page %s', 'plazarecoleta' ), max( $paged, $page ) );

	// Return the new title to wp_title():
	return $title;
}
add_filter( 'wp_title', 'plazarecoleta_filter_wp_title', 10, 2 );

/**
 * Get our wp_nav_menu() fallback, wp_page_menu(), to show a home link.
 *
 * To override this in a child theme, remove the filter and optionally add
 * your own function tied to the wp_page_menu_args filter hook.
 *
 * @since plazarecoleta 1.0
 */
function plazarecoleta_page_menu_args( $args ) {
	$args['show_home'] = true;
	return $args;
}
add_filter( 'wp_page_menu_args', 'plazarecoleta_page_menu_args' );

/**
 * Register Google font for plazarecoleta.
 *
 * @since plazarecoleta 1.0
 *
 * @return string
 */
function plazarecoleta_font_url() {
	$font_url = '';
	/*
	 * Translators: If there are characters in your language that are not supported
	 * by Lato, translate this to 'off'. Do not translate into your own language.
	 */
	if ( 'off' !== _x( 'on', 'Font: on or off', 'plazarecoleta' ) ) {
		$font_url = add_query_arg( 'family','Roboto:400,300,400italic,700|Roboto+Slab', "//fonts.googleapis.com/css" );

	}

	return $font_url;
}

/**
 * Enqueue scripts and styles for the front end.
 *
 * @since plazarecoleta 1.0
 *
 * @return void
 */
function plazarecoleta_scripts() {
	// Add font, used in the main stylesheet.
	wp_enqueue_style( 'plazarecoleta-font', plazarecoleta_font_url(), array(), null );
	
	// Add Genericons font, used in the main stylesheet.
	wp_enqueue_style( 'normalize', get_template_directory_uri() . '/css/normalize.css', array(), '1.0.1' );

	// Load our main stylesheet.
	wp_enqueue_style( 'plazarecoleta-style', get_stylesheet_uri(), array( 'normalize' ) );

	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
	
}
add_action( 'wp_enqueue_scripts', 'plazarecoleta_scripts' );


/**
 * Enqueue Google fonts style to admin screen for custom header display.
 *
 * @since plazarecoleta 1.0
 *
 * @return void
 */
function plazarecoleta_admin_fonts() {
	wp_enqueue_style( 'plazarecoleta-font', plazarecoleta_font_url(), array(), null );
}
add_action( 'admin_print_scripts-appearance_page_custom-header', 'plazarecoleta_admin_fonts' );



/**
 * Sets the post excerpt length to 40 characters.
 *
 * To override this length in a child theme, remove the filter and add your own
 * function tied to the excerpt_length filter hook.
 *
 * @since plazarecoleta 1.0
 * @return int
 */
function plazarecoleta_excerpt_length( $length ) {
	return 30;
}
add_filter( 'excerpt_length', 'plazarecoleta_excerpt_length' );

/**
 * Returns a "Continue Reading" link for excerpts
 *
 * @since plazarecoleta 1.0
 * @return string "Continue Reading" link
 */
function plazarecoleta_continue_reading_link() {
	return;
}

/**
 * Find out if blog has more than one category.
 *
 * @since plazarecoleta 1.0
 *
 * @return boolean true if blog has more than 1 category
 */
function plazarecoleta_categorized_blog() {
	if ( false === ( $all_the_cool_cats = get_transient( 'simple_category_count' ) ) ) {
		// Create an array of all the categories that are attached to posts
		$all_the_cool_cats = get_categories( array(
			'hide_empty' => 1,
		) );

		// Count the number of categories that are attached to the posts
		$all_the_cool_cats = count( $all_the_cool_cats );

		set_transient( 'simple_category_count', $all_the_cool_cats );
	}

	if ( 1 !== (int) $all_the_cool_cats ) {
		// This blog has more than 1 category so simple_categorized_blog should return true
		return true;
	} else {
		// This blog has only 1 category so simple_categorized_blog should return false
		return false;
	}
}


/**
 * Replaces "[...]" (appended to automatically generated excerpts) with an ellipsis and plazarecoleta_continue_reading_link().
 *
 * To override this in a child theme, remove the filter and add your own
 * function tied to the excerpt_more filter hook.
 *
 * @since plazarecoleta 1.0
 * @return string An ellipsis
 */
function plazarecoleta_auto_excerpt_more( $more ) {
	return ' &hellip;' . plazarecoleta_continue_reading_link();
}
add_filter( 'excerpt_more', 'plazarecoleta_auto_excerpt_more' );

/**
 * Adds a pretty "Continue Reading" link to custom post excerpts.
 *
 *
 * @since plazarecoleta 1.0
 * @return string Excerpt with a pretty "Continue Reading" link
 */
function plazarecoleta_custom_excerpt_more( $output ) {
	if ( has_excerpt() && ! is_attachment() ) {
		$output .= plazarecoleta_continue_reading_link();
	}
	return $output;
}
add_filter( 'get_the_excerpt', 'plazarecoleta_custom_excerpt_more' );

/**
 * Remove inline styles printed when the gallery shortcode is used.
 *
 * Galleries are styled by the theme in plazarecoleta's style.css.
 *
 * @since plazarecoleta 1.0
 * @return string The gallery style filter, with the styles themselves removed.
 */
function plazarecoleta_remove_gallery_css( $css ) {
	return preg_replace( "#<style type='text/css'>(.*?)</style>#s", '', $css );
}
add_filter( 'gallery_style', 'plazarecoleta_remove_gallery_css' );

if ( ! function_exists( 'plazarecoleta_comment' ) ) :
/**
 * Template for comments and pingbacks.
 *
 * To override this walker in a child theme without modifying the comments template
 * simply create your own plazarecoleta_comment(), and that function will be used instead.
 *
 * Used as a callback by wp_list_comments() for displaying the comments.
 *
 * @since plazarecoleta 1.0
 */
function plazarecoleta_comment( $comment, $args, $depth ) {
	$GLOBALS['comment'] = $comment;
	switch ( $comment->comment_type ) :
		case '' :
	?>
	<li <?php comment_class(); ?> id="li-comment-<?php comment_ID(); ?>">
		<article id="comment-<?php comment_ID(); ?>">
			<div class="comment-author vcard">
				<?php echo get_avatar( $comment, 40 ); ?>
				<?php printf( __( '%s <span class="says">dice:</span>', 'plazarecoleta' ), sprintf( '<cite class="fn">%s</cite>', get_comment_author_link() ) ); ?>
			</div><!-- .comment-author .vcard -->
			<?php if ( $comment->comment_approved == '0' ) : ?>
				<em><?php _e( 'Your comment is awaiting moderation.', 'plazarecoleta' ); ?></em>
				<br />
			<?php endif; ?>
			<footer class="comment-meta commentmetadata"><a href="<?php echo esc_url( get_comment_link( $comment->comment_ID ) ); ?>">
				<?php
					/* translators: 1: date, 2: time */
					printf( __( '%1$s at %2$s', 'plazarecoleta' ), get_comment_date(),  get_comment_time() ); ?></a><?php edit_comment_link( __( '(Edit)', 'plazarecoleta' ), ' ' );
				?>
			</footer><!-- .comment-meta .commentmetadata -->
			<div class="comment-body"><?php comment_text(); ?></div>
			<div class="reply">
				<?php comment_reply_link( array_merge( $args, array( 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?>
			</div><!-- .reply -->
		</article><!-- #comment-##  -->
	<?php
			break;
		case 'pingback'  :
		case 'trackback' :
	?>
	<li class="post pingback">
		<p><?php _e( 'Pingback:', 'plazarecoleta' ); ?> <?php comment_author_link(); ?><?php edit_comment_link( __('(Edit)', 'plazarecoleta'), ' ' ); ?></p>
	<?php
			break;
	endswitch;
}
endif;

/**
 * Register widgetized areas, including two sidebars and four widget-ready columns in the footer.
 *
 * To override plazarecoleta_widgets_init() in a child theme, remove the action hook and add your own
 * function tied to the init hook.
 *
 * @since plazarecoleta 1.0
 * @uses register_sidebar
 */
function plazarecoleta_widgets_init() {
	// Area 1, located at the top of the sidebar.
	register_sidebar( array(
		'name' => __( 'Main Sidebar', 'plazarecoleta' ),
		'id' => 'primary-widget-area',
		'description' => __( 'Main Sidebar Widget', 'plazarecoleta' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<h4 class="widget-title">',
		'after_title' => '</h4>',
	) );

	// Area 3, located in the footer. Empty by default.
	register_sidebar( array(
		'name' => __( 'Footer Area One', 'plazarecoleta' ),
		'id' => 'first-footer-widget-area',
		'description' => __( 'An optional widget area for your site footer', 'plazarecoleta' ),
		'before_widget' => '<li id="%1$s" class="widget-container %2$s">',
		'after_widget' => '</li>',
		'before_title' => '<h4 class="widget-title">',
		'after_title' => '</h4>',
	) );


}
/** Register sidebars by running plazarecoleta_widgets_init() on the widgets_init hook. */
add_action( 'widgets_init', 'plazarecoleta_widgets_init' );

/**
 * Removes the default styles that are packaged with the Recent Comments widget.
 *
 * To override this in a child theme, remove the filter and optionally add your own
 * function tied to the widgets_init action hook.
 *
 * @since plazarecoleta 1.0
 */
function plazarecoleta_remove_recent_comments_style() {
	global $wp_widget_factory;
	remove_action( 'wp_head', array( $wp_widget_factory->widgets['WP_Widget_Recent_Comments'], 'recent_comments_style' ) );
}
add_action( 'widgets_init', 'plazarecoleta_remove_recent_comments_style' );

if ( ! function_exists( 'plazarecoleta_posted_on' ) ) :
/**
 * Prints HTML with meta information for the current post—date/time and author.
 *
 * @since plazarecoleta 1.0
 */
function plazarecoleta_posted_on() {
	// BP: slight modification to plazarecoleta function, converting single permalink to multi-archival link
	// Y = 2012
	// F = September
	// m = 01–12
	// j = 1–31
	// d = 01–31
printf( __( '<span class="sep">Posted on </span><a href="%1$s" title="%2$s" rel="bookmark"><time class="entry-date" datetime="%3$s" pubdate>%4$s</time></a></span>', 'plazarecoleta' ),
		esc_url( get_permalink() ),
		esc_attr( get_the_time() ),
		esc_attr( get_the_date( 'c' ) ),
		esc_html( get_the_date() ),
		esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ),
		esc_attr( sprintf( __( 'View all posts by %s', 'plazarecoleta' ), get_the_author() ) ),
		get_the_author()
	);
}
endif;

if ( ! function_exists( 'plazarecoleta_posted_in' ) ) :
/**
 * Prints HTML with meta information for the current post (category, tags and permalink).
 *
 * @since plazarecoleta 1.0
 */
function plazarecoleta_posted_in() {
	// Retrieves tag list of current post, separated by commas.
	$tag_list = get_the_tag_list( '', ', ' );
	if ( $tag_list ) {
		$posted_in = __( 'This entry was posted in %1$s and tagged %2$s.', 'plazarecoleta' );
	} elseif ( is_object_in_taxonomy( get_post_type(), 'category' ) ) {
		$posted_in = __( 'This entry was posted in %1$s.', 'plazarecoleta' );
	} else {
		$posted_in = __( 'Bookmark the <a href="/%3$s/" rel="bookmark">permalink</a>.', 'plazarecoleta' );
	}

	// Prints the string, replacing the placeholders.
	printf(
		$posted_in,
		get_the_category_list( ', ' ),
		$tag_list,
		get_permalink(),
		the_title_attribute( 'echo=0' )
	);
}
endif;

if ( ! function_exists( 'simple_paging_nav' ) ) :
/**
 * Display navigation to next/previous set of posts when applicable.
 *
 * @since plazarecoleta 1.0
 *
 * @return void
 */
function plazarecoleta_paging_nav() {
	// Don't print empty markup if there's only one page.
	if ( $GLOBALS['wp_query']->max_num_pages < 2 ) {
		return;
	}

	$paged        = get_query_var( 'paged' ) ? intval( get_query_var( 'paged' ) ) : 1;
	$pagenum_link = html_entity_decode( get_pagenum_link() );
	$query_args   = array();
	$url_parts    = explode( '?', $pagenum_link );

	if ( isset( $url_parts[1] ) ) {
		wp_parse_str( $url_parts[1], $query_args );
	}

	$pagenum_link = remove_query_arg( array_keys( $query_args ), $pagenum_link );
	$pagenum_link = trailingslashit( $pagenum_link ) . '%_%';

	$format  = $GLOBALS['wp_rewrite']->using_index_permalinks() && ! strpos( $pagenum_link, 'index.php' ) ? 'index.php/' : '';
	$format .= $GLOBALS['wp_rewrite']->using_permalinks() ? user_trailingslashit( 'page/%#%', 'paged' ) : '?paged=%#%';

	// Set up paginated links.
	$links = paginate_links( array(
		'base'     => $pagenum_link,
		'format'   => $format,
		'total'    => $GLOBALS['wp_query']->max_num_pages,
		'current'  => $paged,
		'mid_size' => 1,
		'add_args' => array_map( 'urlencode', $query_args ),
		'prev_text' => __( '&larr; Previous', 'simple' ),
		'next_text' => __( 'Next &rarr;', 'simple' ),
	) );

	if ( $links ) :

	?>
	<nav class="navigation paging-navigation" role="navigation">
		<h1 class="screen-reader-text"><?php _e( 'Posts navigation', 'simple' ); ?></h1>
		<div class="pagination loop-pagination">
			<?php echo $links; ?>
		</div><!-- .pagination -->
	</nav><!-- .navigation -->
	<?php
	endif;
}
endif;

/**
 * Add General Options
 *
 * @since plazarecoleta 1.0
 *
 * @return void
 */
	require_once(TEMPLATEPATH . '/theme-admin/general-options.php');
	
	function plazarecoleta_complete_version_removal() {
		return '';
	}
	add_filter('the_generator', 'plazarecoleta_complete_version_removal');


/**
 * Search Form
 *
 * @since plazarecoleta 1.0
 *
 * @return void
 */
	function plazarecoleta_search_form ( $form ) {
		$form = '<form role="search" method="get" id="searchform" action="' . home_url( '/' ) . '" >
		<div><label class="screen-reader-text" for="s">' . __('Search for:') . '</label>
		<input type="search" placeholder="Search for..." value="' . get_search_query() . '" name="s" id="s" />
		<input type="submit" id="searchsubmit" value="'. esc_attr__('Search') .'" />
		</div>
		</form>';
		return $form;
	}
	add_filter( 'get_search_form', 'plazarecoleta_search_form' );

// added per WP upload process request
if ( function_exists( 'add_theme_support' ) ) {
	add_theme_support( 'post-thumbnails' );
}

/**
 *  Adds excerpt on pages
 */
 
add_post_type_support( 'page', 'excerpt');

/**
 * Post Custom Depts
 *
 * @since plazarecoleta 1.0
 *
 * @return void
 */
 
add_action('init', 'depts_register');
 
function depts_register () {
 
$labels = array(
'name' => _x('Departamentos', 'post type general name'),
'singular_name' => _x('Departamento', 'post type singular name'),
'add_new' => _x('Añadir nuevo', 'proyecto item'),
'add_new_item' => __('Añadir nuevo'),
'edit_item' => __('Editar departamento'),
'new_item' => __('Nuevo departamento'),
'view_item' => __('Ver proyecto'),
'search_items' => __('Buscar'),
'not_found' => __('No se ha encontrado nada'),
'not_found_in_trash' => __('No se ha encontrado nada en la papelera'),
'parent_item_colon' => ''
);
 
$args = array(
'labels' => $labels,
'public' => true,
'has_archive' => true,
'publicly_queryable' => true,
'show_ui' => true,
'query_var' => true,
'capability_type' => 'page',
'hierarchical' => false,
'menu_position' => null,
'supports' => array('title','editor','thumbnail','excerpt', 'page-attributes'),
'menu_icon'            => get_template_directory_uri() . '/images/elements/house.png'
);
 
     register_post_type( 'depts', $args );
     flush_rewrite_rules();
}
/**
 * Admin menu custom
 *
 * @since plazarecoleta 1.0
 *
 * @return void
 */
$editor = get_role('editor');
// add $cap capability to this role object
$editor->add_cap('edit_theme_options');
$editor->remove_cap('manage_links');

function edit_admin_menus() {
	global $menu;

	remove_menu_page('edit-comments.php'); // Remove the Tools Menu
	remove_menu_page('edit.php'); // Remove the Tools Menu
}
add_action( 'admin_menu', 'edit_admin_menus' );

function get_id_by_slug($page_slug) {
	$page = get_page_by_path($page_slug);
	if ($page) {
		return $page->ID;
	} else {
		return null;
	}
}

?>